# --- Server kết nối chính (Tailscale / cloud) ---
server.host=100.67.91.8
server.port=5000

# --- Cấu hình DB cho chế độ LOCAL ---
local.db.url=jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
local.db.username=root
local.db.password=